### ISSUE TITLE
Be able to use merge-me-action from a workflow_run event

### ISSUE THREAD

**Issue by sbrunner** [ridedott/merge-me-action#616]
**What do you want to achieve?**

It should be possible to lunch the action on a `workflow_run`action, with workflow like this:

```yaml
name: Auto merge Dependabot updates

on:
  workflow_run:
    workflows:
      - Workflow 1
      - Workflow 2
    types:
      - completed

jobs:
  auto-merge:
    name: Auto merge
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

In this case, we get an event like this (from `github` context) (largely simplified):
```json
{
  "event_name": "workflow_run",
  "event": {
    "action": "completed",
    "workflow_run": {
      "conclusion": "success",
      "pull_requests": [
        {
          "number": <number>,
          "url": "https://api.github.com/repos/<org>/<repo>/pulls/<number>"
        }
      ]
    }
  }
}
```

**What is the current way of working?**

Actually, the merge is done by Dependabot v1

**How much does it hurt?**

I can't migrate to Dependabot v2, and the solution of putting merge-me-action at the ends of my main workflow doesn't work well because in some cases I should wait on more than one workflow.
