### ISSUE TITLE
Question about how to auto-merge PRs with specific label

### ISSUE THREAD

**Issue by steven-murray** [ridedott/merge-me-action#645]
**What do you want to achieve?**

Most likely, this is already possible, and I just don't get it from the docs. What I'd like to do is back-merge `master` into `dev` automatically. Both `master` and `dev` are protected (`dev` requires a review and CI passing). Currently, when I merge a release into `master`, a new PR is automatically created (using a Github Action) to pull `master` back to `dev`. I'd like this to be auto-merged, with the only required criteria being that it's up-to-date (i.e. I don't want to have to review it, or for it to pass CI tests, since that's redundant). However, I don't want the Merge-Me action to automatically merge other PRs to `dev`!

Is there a way of constraining `Merge-Me` to operate only on PRs that have a certain label, for example? (Currently these PRs are labeled with `auto-pr`).

**What is the current way of working?**

Currently, I just do it manually -- I have to go to Github and click merge.

**How much does it hurt?**

It's fairly annoying,  especially as I'm _sure_ someone must have fixed this problem before!

**Comment by merlinnot** [comment]
Hi! You can do that using native GitHub Actions functionalities. Jobs support `if`s (see [docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif)). You can add an if statement that checks the label, using [context and expressions](https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions).

To easily check what values are available in the context, you can add this job:

```yaml
on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```

**Comment by dunyakirkali** [comment]
@steven-murray ☝️ does answer your question right?

**Comment by steven-murray** [comment]
Hi @merlinnot and @dunyakirkali sorry for the slow response -- I have a million other projects and haven't had time to get back to this one. I believe the response has the answer I need, but I will confirm once I actually implement it -- hopefully over the next few days.

Feel free to close the issue if that helps you -- I will re-open if anything goes wrong.

Thanks for the answer!

**Comment by steven-murray** [comment]
So, for completeness, here's the workflow I used in the end:

```
name: Merge me!

on:
  pull_request:
    types:
      - labeled
      - ready_for_review
      - reopened
      - unlocked

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-pr')
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          # This must be used as GitHub Actions token does not support
          # pushing to protected branches.
          GITHUB_TOKEN: ${{ secrets.BUMP_VERSION }}
          GITHUB_LOGIN: steven-murray
          MERGE_METHOD: REBASE
```

I do get a strange error: 

```
An error ocurred while merging the Pull Request. This is usually caused by the base branch being out of sync with the target branch. In this case, the base branch must be rebased. Some tools, such as Dependabot, do that automatically.
```
But it still seems to merge the PR fine...
