### ISSUE TITLE
The action seems to be failing since yesterday

### ISSUE THREAD

**Issue by char0n** [ridedott/merge-me-action#814]
**How would you describe the issue?**

The action is not working anymore. It doesn't merge depedabot PRs

**How can we reproduce the issue?**

Example of failure: https://github.com/char0n/json-api-merge/pull/224/checks?check_run_id=2063134861

**What are the expected results?**

The action merges the PR

**What are the actual results?**

Action fails on 
```sh
/home/runner/work/_actions/ridedott/merge-me-action/master/node_modules/@actions/github/lib/internal/utils.js:23
const httpClient = __importStar(require("@actions/http-client"));
```

**How much does it hurt?**

A lot ;]

**Comment by sluukkonen** [comment]
The reason: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

**Comment by char0n** [comment]
What options do we have here? I can think of placing an issue comment of `@dependabot merge` instead of actually merging the PR.

**Comment by char0n** [comment]
Some other related material: https://securitylab.github.com/research/github-actions-preventing-pwn-requests

**Comment by JrSchild** [comment]
Hi guys, we are working on a fix. Many resources mention options like using `pull_request_target` or uploading artifacts with the PR number. While using `pull_request_target` is unsafe and uploading artifacts not very ergonomic, I've found a way to make it work with just a separate workflow because the pull request number is provided in the context.

It still requires to trigger on the `workflow_run` event. I've just POC-ed it and it started merging! One thing I noticed was that some suggestions showed filtering on the `pull_request` event of the triggered workflow, but I'm going with `push` for now.

We will continue to properly implement it and attempt to tackle additional problems we will find in the future. Sorry for this taking a bit of time.

**Comment by char0n** [comment]
Meanwhile I've updated the article I wrote on the auto-merge subject with a new section with a workaround: https://www.linkedin.com/pulse/how-keep-your-npm-dependencies-up-to-date-without-wasting-gorej/; search for "Update: 16.3.2021"

The workaround uses another GitHub Action for the time being until the problem is fixed with this GitHub Action.

**Comment by JrSchild** [comment]
@char0n @sluukkonen This is now fixed with a separate workflow action thanks to @sbrunner.

As mentioned before, `pull_request_target` is not safe to use so we opted to use `workflow_run`. We just need to update the documentation to reflect it. This will be the new configuration:
```yaml
# .github/workflows/merge-me.yaml

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types:
      - completed

jobs:
  merge-me:
    name: Merge me!
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    timeout-minutes: 5
```

@char0n Could you re-update your article?
