### ISSUE TITLE
Use multiple GITHUB_LOGIN

### ISSUE THREAD

**Issue by Nick-Mazuk** [ridedott/merge-me-action#815]
**What do you want to achieve?**

It would be great to be able to use multiple GitHub logins instead of just one (e.g., only `dependabot[bot]`). This would allow for greater automation possibilities.

For instance, in my case, I'm creating a CD pipeline. Twice per week, a GitHub action starts a PR from main into production. Then another action (the one that using this "merge-me" action) will merge the PR after all tests pass. For this, I can just whitelist 'github-actions[bot]' instead of the default dependabot. However, sometimes it's good manually push things to production (e.g., there's a nasty bug in production that needs to be fixed ASAP). To streamline things, a user (me) should just need to start a PR from main to production, then the actions do the rest of the work. But since I'm not a `github-actions[bot]`, the PR will not be automatically merged.

```yml
- name: Merge me!
        uses: ridedott/merge-me-action@v2.2.18
        with:
          GITHUB_LOGIN:
            - 'github-actions[bot]'
            - 'dependabot[bot]'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

or perhaps set a wildcard:

```yml
- name: Merge me!
        uses: ridedott/merge-me-action@v2.2.18
        with:
          GITHUB_LOGIN: '*'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**What is the current way of working?**

You can list the merge-me action multiple times, each with a different GITHUB_LOGIN specified. However, this means that all actions will run longer (merge-me always run multiple times), it's not DRY, and it doesn't scale.

**How much does it hurt?**

7/10
